# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sm6150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a60q a70q a70s a71 m40dd m51 r1q,$(TARGET_DEVICE)),)

endif
